import type { Metadata } from "next";
import {
  montserrat,

} from "@/lib/fonts";

import "./globals.css";
// app/layout.tsx
import "remixicon/fonts/remixicon.css";

export const metadata: Metadata = {
  title: "MultiCart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` ${montserrat.variable}
    h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
